### ISSUE TITLE
Is it possible to process XML response?

### ISSUE THREAD

**Issue by ppazos** [bulkan/robotframework-requests#230]
In the readme there is a resp.json(), is there an equivalent resp.xml() to parse XML responses?

**Comment by Barbario** [comment]
@ppazos, I've been struggling with a similar issue with some legacy services and was wondering if you found a solution to this.  My current workaround is to make a second request and save it to a list variable . Which gives me a comma separated list  for each line of the XML.  This is a bit of a mess to work with but it's what I have found so far.

`
@{respXML}=    Get Request      mySite      /feed/android
log   ${respXML}
`

**Comment by Barbario** [comment]
After searching a couple more hours I've determined this to be the temporary work around.  Hope this helps as it worked for me.  I'm sure someone else has thought of a better solution out there, I just haven't found it yet.

1.  Had to convert some stuff so that I could work with the list which required "Collections" Library.
2. Created a new keyword which would take the list returned and loop it to create a string
3. Take the string version and converted it to XML using the XML Library.
4. All the logging is optional, I left it in for debugging purposes.

```
Library         RequestsLibrary
Library         Collections
Library         XML

Test Name
    Create Session      alias      https://yahoo.com    verify=${true}    max_retries=3
    ${resp}=    Get Request         alias      /feed
    @{respXML}=    Get Request      alias      /feed
    log list    ${respXML}
    log    ${resp.status_code}
    should be equal as integers    ${resp.status_code}    200
    ${strXML}=    Loop the XML    ${respXML}
    log    ${strXML}
    ${root}=    Parse XML    ${strXML}
    log element    ${root}

*** Keywords ***
Loop the XML
    [Arguments]  ${list}
    ${XML}=    set variable    ${EMPTY}
    FOR     ${item}    IN    @{list}
        log    ${item}
        ${line}=    get from list    ${list}    0
        log    ${line}
        ${XML}=    catenate    SEPARATOR=    ${XML}    ${line}
        log    ${XML}
        remove from list    ${list}    0
        log    ${list}
    END
    [Return]    ${XML}
```

**Comment by ppazos** [comment]
@Barbario thanks, I ended up using the XML library and parsing the XML using the Parse XML keyword.

It would be nice to have a .xml() function like there is with .json() integrated into this library, but using the XML library directly works.
